<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| PDF document strings
|--------------------------------------------------------------------------
|
| Strings rendered into PDF documents (receipts, invoices, quotes,
| analytics exports) via DomPDF.  DomPDF cannot fetch external CSS
| or stylesheets, so PDF templates inline their CSS, but human-
| readable copy still comes through these translation keys so
| buyers can adapt or translate without touching the Blade views.
|
| Placeholders use Laravel's :placeholder convention; pass values via
| __('pdf.key', ['placeholder' => $value]).
|
*/

return [

    // ─── Billing receipt (receipt-pdf.blade.php) ─────────────────────
    'receipt' => [
        'doc_title'          => 'Receipt :number',
        'title'              => 'Receipt',
        'issued'             => 'Issued :date',
        'from'               => 'From',
        'billed_to'          => 'Billed to',
        'anonymized'         => '<anonymized>',
        'gdpr_anonymized'    => 'Workspace deleted under GDPR Article 17. Tax record retained.',
        'vat_label'          => 'VAT/GST: :number',
        'th_description'     => 'Description',
        'th_plan'            => 'Plan',
        'th_amount'          => 'Amount',
        'subscription_via'   => 'Subscription payment via :gateway',
        'ref'                => 'Ref: :ref',
        'total_paid'         => 'Total paid',
        'payment_method'     => 'Payment method',
        'auto_footer'        => 'This receipt was generated automatically.  For tax queries, contact :company support.',

        // ─── Gateway names (Pass 22) ─────────────────────────────
        // Stripe/PayPal/Razorpay/Paystack are brand names and ship
        // verbatim — they don't translate.  'manual' however is plain
        // English and needs a localised label so non-English tenants
        // don't see "Manual" mid-receipt.
        'gateway_stripe'     => 'Stripe',
        'gateway_paypal'     => 'PayPal',
        'gateway_razorpay'   => 'Razorpay',
        'gateway_paystack'   => 'Paystack',
        'gateway_manual'     => 'Manual',
    ],

    // ─── Customer invoice (public/invoice/pdf.blade.php) ─────────────
    'invoice' => [
        'doc_title'     => 'Invoice :number',
        'label'         => 'INVOICE',
        'issued'        => 'Issued :date',
        'due'           => 'Due :date',
        'paid_stamp'    => 'Paid',
        'from'          => 'From',
        'bill_to'       => 'Bill to',
        'th_item'       => 'Item',
        'th_qty'        => 'Qty',
        'th_unit'       => 'Unit (:currency)',
        'th_total'      => 'Total (:currency)',
        'subtotal'      => 'Subtotal',
        'discount'      => 'Discount',
        'tax'           => 'Tax (:rate%)',
        'grand_total'   => 'Grand Total',
        'paid'          => 'Paid',
        'amount_due'    => 'Amount due',
        'generated'     => 'Generated :date · :app',
    ],

    // ─── Customer quote (public/quote/pdf.blade.php) ─────────────────
    'quote' => [
        'doc_title'          => 'Quote :number',
        'label'              => 'QUOTE',
        'issued'             => 'Issued :date',
        'valid_until'        => 'Valid until :date',
        'from'               => 'From',
        'to'                 => 'To',
        'introduction'       => 'Introduction',
        'th_item'            => 'Item',
        'th_qty'             => 'Qty',
        'th_unit'            => 'Unit (:currency)',
        'th_total'           => 'Total (:currency)',
        'subtotal'           => 'Subtotal',
        'discount'           => 'Discount',
        'tax'                => 'Tax (:rate%)',
        'grand_total'        => 'Grand Total',
        'terms_conditions'   => 'Terms & Conditions',
        'signed_by'          => 'by :name on :date (IP :ip)',
        'signed_label'       => 'Signed',
        'generated'          => 'Generated :date · :app',
    ],

    // ─── Analytics PDF report (exports/pdf-report.blade.php) ─────────
    'report' => [
        'exported'      => 'Exported: :time',
        'analytics'     => ':app Analytics',
        'period'        => 'Period: :from — :to',
        'filters'       => 'Filters:',
        'no_data'       => 'No data available for the selected period.',
        'footer'        => 'Generated by :brand · :time · Total rows: :count',
    ],

];
