<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Data Processing Agreement (DPA) — translation strings
|--------------------------------------------------------------------------
|
| Edit this file to localise or adapt the DPA template generated by
| /super-admin/legal/dpa.  Buyers can:
|   - Translate to additional locales by copying this file to
|     lang/<locale>/legal_dpa.php and changing the values.
|   - Re-word any clause to match their jurisdiction or counsel's
|     guidance without touching the view template.
|   - Add or remove sections — keep the section numbering consistent
|     between the keys here and the view at
|     resources/views/legal/dpa-template.blade.php.
|
| Placeholders:
|   :date      — render-date in Y-m-d format
|   :datetime  — render-date in Y-m-d H:i format
|   :company   — operator's company name (config/leadhub.php)
|
*/

return [

    'document_title'   => 'Data Processing Agreement (Template)',
    'heading'          => 'Data Processing Agreement',
    'meta_generated'   => 'Template generated :date by :company',

    'notice' => 'Template only — review with qualified legal counsel before signing. '
              . 'This document is provided as a starting point and does not constitute legal advice.',

    // --- Section 1: Parties --------------------------------------------------
    'section_1_title'             => '1. Parties',
    'section_1_intro'             => 'This Data Processing Agreement ("DPA") forms part of the Master Services Agreement between:',
    'section_1_controller_label'  => 'The Controller:',
    'section_1_controller_value'  => '____________________________________________________ (the customer)',
    'section_1_processor_label'   => 'The Processor:',
    'section_1_processor_value'   => ':company (the service provider operating this CRM)',

    // --- Section 2: Subject Matter and Duration ------------------------------
    'section_2_title' => '2. Subject Matter and Duration',
    'section_2_body'  => 'The Processor processes Personal Data on behalf of the Controller for the purpose of providing '
                       . 'the Customer Relationship Management (CRM) services. This DPA remains in force for the duration '
                       . 'of the Master Services Agreement and any applicable post-termination data-export window.',

    // --- Section 3: Nature and Purpose of Processing -------------------------
    'section_3_title' => '3. Nature and Purpose of Processing',
    'section_3_body'  => 'Storage, organisation, retrieval, transmission, and deletion of contact records, communications, '
                       . 'and related operational data submitted by the Controller or by the Controller\'s data subjects '
                       . '(e.g. via lead capture forms).',

    // --- Section 4: Categories of Data Subjects and Personal Data ------------
    'section_4_title'  => '4. Categories of Data Subjects and Personal Data',
    'section_4_item_1' => 'Data subjects: leads, prospects, customers, and authorised users of the Controller.',
    'section_4_item_2' => 'Personal data: name, email, phone number, postal address, IP address, browser metadata, '
                        . 'and any free-text content the Controller chooses to store.',
    'section_4_item_3' => 'Special-category data: not collected by default; the Controller is responsible for any '
                        . 'special-category data they choose to store and must inform the Processor in writing.',

    // --- Section 5: Obligations of the Processor -----------------------------
    'section_5_title'  => '5. Obligations of the Processor',
    'section_5_item_1' => 'Process Personal Data only on documented instructions from the Controller.',
    'section_5_item_2' => 'Ensure persons authorised to process Personal Data are subject to a duty of confidentiality.',
    'section_5_item_3' => 'Implement appropriate technical and organisational measures (Article 32 GDPR), including '
                        . 'encryption at rest and in transit, access logging, and regular backups.',
    'section_5_item_4' => 'Notify the Controller of any Personal Data breach without undue delay and within '
                        . 'seventy-two (72) hours of becoming aware of it.',
    'section_5_item_5' => 'Assist the Controller in fulfilling data-subject rights requests (access, rectification, '
                        . 'erasure, portability, restriction, objection).',

    // --- Section 6: Sub-Processors ------------------------------------------
    'section_6_title' => '6. Sub-Processors',
    'section_6_body'  => 'The Controller authorises the Processor to engage sub-processors (e.g. infrastructure providers, '
                       . 'email-delivery services, payment gateways). The Processor will maintain a current list of '
                       . 'sub-processors and will notify the Controller in writing of any addition or replacement at '
                       . 'least thirty (30) days in advance, giving the Controller the opportunity to object.',

    // --- Section 7: International Transfers ---------------------------------
    'section_7_title' => '7. International Transfers',
    'section_7_body'  => 'Where Personal Data is transferred outside the European Economic Area, the Processor will rely '
                       . 'on European Commission Standard Contractual Clauses (SCCs) or another lawful transfer mechanism '
                       . 'set out in Chapter V of the GDPR.',

    // --- Section 8: Audits and Inspections ----------------------------------
    'section_8_title' => '8. Audits and Inspections',
    'section_8_body'  => 'The Processor will make available to the Controller all information necessary to demonstrate '
                       . 'compliance with this DPA and will allow for and contribute to audits, including inspections, '
                       . 'conducted by the Controller or another auditor mandated by the Controller, at the Controller\'s '
                       . 'cost and on reasonable advance notice.',

    // --- Section 9: Deletion or Return of Personal Data ---------------------
    'section_9_title' => '9. Deletion or Return of Personal Data',
    'section_9_body'  => 'On termination of the Master Services Agreement, the Processor will, at the choice of the '
                       . 'Controller, delete or return all Personal Data and delete existing copies, unless retention is '
                       . 'required by law. A standard sixty (60) day post-termination export window is available.',

    // --- Section 10: Liability and Governing Law ----------------------------
    'section_10_title' => '10. Liability and Governing Law',
    'section_10_body'  => 'Liability under this DPA is governed by the Master Services Agreement. The DPA is governed by '
                        . 'the law specified in the Master Services Agreement; if none is specified, the law of the '
                        . 'Processor\'s principal place of business applies.',

    // --- Signature block ----------------------------------------------------
    'sig_controller' => 'The Controller',
    'sig_processor'  => 'The Processor — :company',
    'sig_name'       => 'Name:',
    'sig_title'      => 'Title:',
    'sig_date'       => 'Date:',

    // --- Footer -------------------------------------------------------------
    'footer' => 'Generated :datetime UTC · :company · This template is informational '
              . 'and not a substitute for qualified legal advice.',

];
