<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Data Processing Agreement (DPA) — translation strings
|--------------------------------------------------------------------------
|
| Edit this file to localise or adapt the DPA template generated by
| /super-admin/legal/dpa.  Buyers can:
|   - Translate to additional locales by copying this file to
|     lang/<locale>/legal_dpa.php and changing the values.
|   - Re-word any clause to match their jurisdiction or counsel's
|     guidance without touching the view template.
|   - Add or remove sections — keep the section numbering consistent
|     between the keys here and the view at
|     resources/views/legal/dpa-template.blade.php.
|
| Placeholders:
|   :date      — render-date in Y-m-d format
|   :datetime  — render-date in Y-m-d H:i format
|   :company   — operator's company name (config/leadhub.php)
|
*/

return [

    'document_title'   => 'Acuerdo de Tratamiento de Datos (Plantilla)',
    'heading'          => 'Acuerdo de Tratamiento de Datos',
    'meta_generated'   => 'Plantilla generada el :date por :company',

    'notice' => 'Solo plantilla — revísela con asesoría legal cualificada antes de firmar. '
              . 'Este documento se proporciona como punto de partida y no constituye asesoramiento legal.',

    // --- Section 1: Parties --------------------------------------------------
    'section_1_title'             => '1. Partes',
    'section_1_intro'             => 'Este Acuerdo de Tratamiento de Datos («DPA») forma parte del Acuerdo Maestro de Servicios entre:',
    'section_1_controller_label'  => 'El Responsable:',
    'section_1_controller_value'  => '____________________________________________________ (el cliente)',
    'section_1_processor_label'   => 'El Encargado:',
    'section_1_processor_value'   => ':company (el proveedor de servicios que opera este CRM)',

    // --- Section 2: Subject Matter and Duration ------------------------------
    'section_2_title' => '2. Objeto y duración',
    'section_2_body'  => 'El Encargado trata Datos Personales por cuenta del Responsable con el fin de prestar '
                       . 'los servicios de Gestión de la Relación con el Cliente (CRM). Este DPA permanece en vigor durante la duración '
                       . 'del Acuerdo Maestro de Servicios y de cualquier período aplicable de exportación de datos tras la terminación.',

    // --- Section 3: Nature and Purpose of Processing -------------------------
    'section_3_title' => '3. Naturaleza y finalidad del tratamiento',
    'section_3_body'  => 'Almacenamiento, organización, recuperación, transmisión y supresión de registros de contactos, comunicaciones, '
                       . 'y datos operativos relacionados enviados por el Responsable o por los interesados del Responsable '
                       . '(p. ej. a través de formularios de captación de clientes potenciales).',

    // --- Section 4: Categories of Data Subjects and Personal Data ------------
    'section_4_title'  => '4. Categorías de interesados y datos personales',
    'section_4_item_1' => 'Interesados: clientes potenciales, prospectos, clientes y usuarios autorizados del Responsable.',
    'section_4_item_2' => 'Datos personales: nombre, correo electrónico, número de teléfono, dirección postal, dirección IP, metadatos del navegador, '
                        . 'y cualquier contenido de texto libre que el Responsable decida almacenar.',
    'section_4_item_3' => 'Datos de categorías especiales: no se recogen por defecto; el Responsable es responsable de cualquier '
                        . 'dato de categoría especial que decida almacenar y debe informar al Encargado por escrito.',

    // --- Section 5: Obligations of the Processor -----------------------------
    'section_5_title'  => '5. Obligaciones del Encargado',
    'section_5_item_1' => 'Tratar los Datos Personales únicamente siguiendo instrucciones documentadas del Responsable.',
    'section_5_item_2' => 'Garantizar que las personas autorizadas para tratar Datos Personales estén sujetas a un deber de confidencialidad.',
    'section_5_item_3' => 'Implementar las medidas técnicas y organizativas adecuadas (artículo 32 del GDPR), incluyendo '
                        . 'cifrado en reposo y en tránsito, registro de accesos y copias de seguridad regulares.',
    'section_5_item_4' => 'Notificar al Responsable cualquier violación de Datos Personales sin dilación indebida y dentro de '
                        . 'las setenta y dos (72) horas siguientes a tener conocimiento de ella.',
    'section_5_item_5' => 'Asistir al Responsable en el cumplimiento de las solicitudes de derechos del interesado (acceso, rectificación, '
                        . 'supresión, portabilidad, limitación, oposición).',

    // --- Section 6: Sub-Processors ------------------------------------------
    'section_6_title' => '6. Subencargados',
    'section_6_body'  => 'El Responsable autoriza al Encargado a contratar subencargados (p. ej., proveedores de infraestructura, '
                       . 'servicios de entrega de correo, pasarelas de pago). El Encargado mantendrá una lista actualizada de '
                       . 'subencargados y notificará al Responsable por escrito cualquier incorporación o sustitución con al menos '
                       . 'treinta (30) días de antelación, dando al Responsable la oportunidad de oponerse.',

    // --- Section 7: International Transfers ---------------------------------
    'section_7_title' => '7. Transferencias internacionales',
    'section_7_body'  => 'Cuando los Datos Personales se transfieran fuera del Espacio Económico Europeo, el Encargado se basará '
                       . 'en las Cláusulas Contractuales Tipo (SCC) de la Comisión Europea o en otro mecanismo de transferencia legítimo '
                       . 'previsto en el Capítulo V del GDPR.',

    // --- Section 8: Audits and Inspections ----------------------------------
    'section_8_title' => '8. Auditorías e inspecciones',
    'section_8_body'  => 'El Encargado pondrá a disposición del Responsable toda la información necesaria para demostrar '
                       . 'el cumplimiento de este DPA y permitirá y contribuirá a auditorías, incluidas inspecciones, '
                       . 'realizadas por el Responsable u otro auditor designado por el Responsable, a costa del Responsable '
                       . 'y con preaviso razonable.',

    // --- Section 9: Deletion or Return of Personal Data ---------------------
    'section_9_title' => '9. Supresión o devolución de los Datos Personales',
    'section_9_body'  => 'A la terminación del Acuerdo Maestro de Servicios, el Encargado, a elección del '
                       . 'Responsable, suprimirá o devolverá todos los Datos Personales y eliminará las copias existentes, salvo que la conservación sea '
                       . 'exigida por ley. Se ofrece un período estándar de exportación post-terminación de sesenta (60) días.',

    // --- Section 10: Liability and Governing Law ----------------------------
    'section_10_title' => '10. Responsabilidad y legislación aplicable',
    'section_10_body'  => 'La responsabilidad bajo este DPA se rige por el Acuerdo Maestro de Servicios. Este DPA se rige por '
                        . 'la legislación especificada en el Acuerdo Maestro de Servicios; si no se especifica ninguna, se aplicará la '
                        . 'legislación del lugar principal de actividad del Encargado.',

    // --- Signature block ----------------------------------------------------
    'sig_controller' => 'El Responsable',
    'sig_processor'  => 'El Encargado — :company',
    'sig_name'       => 'Nombre:',
    'sig_title'      => 'Cargo:',
    'sig_date'       => 'Fecha:',

    // --- Footer -------------------------------------------------------------
    'footer' => 'Generado :datetime UTC · :company · Esta plantilla es informativa '
              . 'y no sustituye a un asesoramiento legal cualificado.',

];
